### ISSUE TITLE
Support for AES

### ISSUE THREAD

**Issue by Kleissner** [saracen/go7z#1]
Any plans for supporting the method `0x6F10701` known as 7zAES?

The package https://github.com/nicholastoddsmith/aesrw provides an AES reader `aesrw.NewReader` that could be used. The only missing part would be generating the AES key out of the user-provided password.

The key function is a deviation of the of SHA256 with multiple rounds. The C implementation is here: https://github.com/kornelski/7z/blob/a6e2c7e401a3e5976e8522de518a169b0d8a7fac/CPP/7zip/Crypto/7zAes.cpp#L37

**Comment by saracen** [comment]
@Kleissner Apologies, I've only just seen this.

On first glance it seems pretty easy to implement. I'll see what I can do.

**Comment by saracen** [comment]
@Kleissner I've now added this.

You can use `SetPassword()` on the reader, or use the `SetPasswordCallback()` function to set a callback that you can use to ask an end-user for input when decryption is required etc.

Closing this now. Feel free to re-open or raise another issue if there's a problem with this implementation.
